export interface StoryInlineImage {
  afterParagraph: number;
  image: {
    url: string;
    source: "pexels";
    pageUrl?: string;
    credit?: string;
  };
  keywordTag?: string;
}

// Generated by scripts/generate-story-images.mjs
export const storyInlineImagesByIndex: Record<number, StoryInlineImage[]> = {
  0: [
    {
      afterParagraph: 2,
      image: {
        url: "https://images.pexels.com/photos/31126245/pexels-photo-31126245.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/silhouette-of-bird-on-branch-at-sunset-31126245/",
        credit: "Tommes Frites",
      },
      keywordTag: "bird",
    },
    {
      afterParagraph: 3,
      image: {
        url: "https://images.pexels.com/photos/30998086/pexels-photo-30998086.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/silhouette-of-bird-at-sunset-on-concrete-beam-30998086/",
        credit: "Sharath G.",
      },
      keywordTag: "family",
    },
  ],
  1: [
    {
      afterParagraph: 2,
      image: {
        url: "https://images.pexels.com/photos/31122087/pexels-photo-31122087.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/cozy-nursery-setting-with-teddy-bears-and-lamp-31122087/",
        credit: "🇻🇳🇻🇳 Việt Anh Nguyễn 🇻🇳🇻🇳",
      },
      keywordTag: "home",
    },
    {
      afterParagraph: 3,
      image: {
        url: "https://images.pexels.com/photos/6974812/pexels-photo-6974812.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/woman-kissing-a-girl-s-forehead-inbed-6974812/",
        credit: "cottonbro studio",
      },
      keywordTag: "family",
    },
  ],
  2: [
    {
      afterParagraph: 2,
      image: {
        url: "https://images.pexels.com/photos/29690637/pexels-photo-29690637.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/graceful-seagull-soaring-in-golden-light-29690637/",
        credit: "nis_ vagabond",
      },
      keywordTag: "bird",
    },
    {
      afterParagraph: 3,
      image: {
        url: "https://images.pexels.com/photos/36296574/pexels-photo-36296574.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/small-bird-perched-on-a-tree-stump-at-sunset-36296574/",
        credit: "ayman kady",
      },
      keywordTag: "home",
    },
  ],
  3: [
    {
      afterParagraph: 2,
      image: {
        url: "https://images.pexels.com/photos/1656092/pexels-photo-1656092.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/landscape-photography-of-road-between-trees-1656092/",
        credit: "Johannes Plenio",
      },
      keywordTag: "forest",
    },
    {
      afterParagraph: 3,
      image: {
        url: "https://images.pexels.com/photos/1102912/pexels-photo-1102912.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/trees-near-pathway-1102912/",
        credit: "Johannes Plenio",
      },
      keywordTag: "bird",
    },
  ],
  4: [
    {
      afterParagraph: 2,
      image: {
        url: "https://images.pexels.com/photos/30789665/pexels-photo-30789665.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/ethereal-forest-path-in-golden-sunset-light-30789665/",
        credit: "Werner Hilversum",
      },
      keywordTag: "forest",
    },
    {
      afterParagraph: 4,
      image: {
        url: "https://images.pexels.com/photos/4084698/pexels-photo-4084698.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/bright-sun-illuminating-pathway-in-forest-at-dawn-4084698/",
        credit: "Johannes Plenio",
      },
      keywordTag: "river",
    },
  ],
  5: [
    {
      afterParagraph: 2,
      image: {
        url: "https://images.pexels.com/photos/28500445/pexels-photo-28500445.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/cozy-bedroom-night-scene-with-table-lamp-28500445/",
        credit: "Hoài  Nam",
      },
      keywordTag: "home",
    },
    {
      afterParagraph: 4,
      image: {
        url: "https://images.pexels.com/photos/6182884/pexels-photo-6182884.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/stuffed-toy-animals-and-string-lights-on-a-bed-6182884/",
        credit: "cottonbro studio",
      },
      keywordTag: "family",
    },
  ],
  6: [
    {
      afterParagraph: 2,
      image: {
        url: "https://images.pexels.com/photos/12032713/pexels-photo-12032713.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/first-day-of-the-moon-12032713/",
        credit: "MAG Photography",
      },
      keywordTag: "moon",
    },
    {
      afterParagraph: 3,
      image: {
        url: "https://images.pexels.com/photos/11922022/pexels-photo-11922022.png?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/moon-in-the-starry-night-sky-11922022/",
        credit: "Felipe Barboza",
      },
      keywordTag: "rabbit",
    },
  ],
  7: [
    {
      afterParagraph: 2,
      image: {
        url: "https://images.pexels.com/photos/27433445/pexels-photo-27433445.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/a-sunset-over-a-river-with-trees-and-water-27433445/",
        credit: "Krzysztof Jaworski-Fotografia",
      },
      keywordTag: "river",
    },
    {
      afterParagraph: 4,
      image: {
        url: "https://images.pexels.com/photos/1039079/pexels-photo-1039079.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/panoramic-photo-of-green-trees-near-river-at-noontime-1039079/",
        credit: "Felix Mittermeier",
      },
      keywordTag: "bird",
    },
  ],
  8: [
    {
      afterParagraph: 2,
      image: {
        url: "https://images.pexels.com/photos/15231173/pexels-photo-15231173.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/view-of-an-egret-walking-in-the-grass-15231173/",
        credit: "Soonam Wooeser",
      },
      keywordTag: "bird",
    },
    {
      afterParagraph: 4,
      image: {
        url: "https://images.pexels.com/photos/9945167/pexels-photo-9945167.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/close-up-of-grass-in-a-meadow-9945167/",
        credit: "Anton Kudryashov",
      },
      keywordTag: "family",
    },
  ],
  9: [
    {
      afterParagraph: 2,
      image: {
        url: "https://images.pexels.com/photos/25384871/pexels-photo-25384871.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/grey-bird-on-a-meadow-25384871/",
        credit: "Tommes Frites",
      },
      keywordTag: "bird",
    },
    {
      afterParagraph: 4,
      image: {
        url: "https://images.pexels.com/photos/34837676/pexels-photo-34837676.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/solitary-bird-soaring-over-tranquil-countryside-at-dusk-34837676/",
        credit: "Robert So",
      },
      keywordTag: "home",
    },
  ],
  10: [
    {
      afterParagraph: 2,
      image: {
        url: "https://images.pexels.com/photos/531853/pexels-photo-531853.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/body-of-water-531853/",
        credit: "Pixabay",
      },
      keywordTag: "river",
    },
    {
      afterParagraph: 4,
      image: {
        url: "https://images.pexels.com/photos/8594380/pexels-photo-8594380.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/green-trees-on-body-of-water-during-dawn-8594380/",
        credit: "Иван Кузнецов",
      },
      keywordTag: "bird",
    },
  ],
  11: [
    {
      afterParagraph: 2,
      image: {
        url: "https://images.pexels.com/photos/6941312/pexels-photo-6941312.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/humidifier-in-a-room-6941312/",
        credit: "cottonbro studio",
      },
      keywordTag: "bedtime",
    },
    {
      afterParagraph: 3,
      image: {
        url: "https://images.pexels.com/photos/29249343/pexels-photo-29249343.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/young-girl-reading-by-soft-light-at-night-29249343/",
        credit: "Boris Hamer",
      },
      keywordTag: "family",
    },
  ],
  12: [
    {
      afterParagraph: 2,
      image: {
        url: "https://images.pexels.com/photos/9112615/pexels-photo-9112615.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/crescent-moon-in-the-blue-sky-9112615/",
        credit: "Chris F",
      },
      keywordTag: "moon",
    },
    {
      afterParagraph: 4,
      image: {
        url: "https://images.pexels.com/photos/7239279/pexels-photo-7239279.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/half-moon-in-purple-sky-at-sunset-7239279/",
        credit: "Diana ✨",
      },
      keywordTag: "home",
    },
  ],
  13: [
    {
      afterParagraph: 2,
      image: {
        url: "https://images.pexels.com/photos/32549248/pexels-photo-32549248.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/serene-pathway-through-lush-woodland-32549248/",
        credit: "Candid Flaneur",
      },
      keywordTag: "forest",
    },
    {
      afterParagraph: 4,
      image: {
        url: "https://images.pexels.com/photos/1102908/pexels-photo-1102908.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/foggy-path-1102908/",
        credit: "Johannes Plenio",
      },
      keywordTag: "home",
    },
  ],
  14: [
    {
      afterParagraph: 2,
      image: {
        url: "https://images.pexels.com/photos/3828097/pexels-photo-3828097.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/white-rabbit-on-green-grass-3828097/",
        credit: "Smooth Click",
      },
      keywordTag: "rabbit",
    },
    {
      afterParagraph: 4,
      image: {
        url: "https://images.pexels.com/photos/3730206/pexels-photo-3730206.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/photo-of-rabbit-3730206/",
        credit: "Lucas",
      },
      keywordTag: "market",
    },
  ],
  15: [
    {
      afterParagraph: 2,
      image: {
        url: "https://images.pexels.com/photos/35240015/pexels-photo-35240015.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/silhouettes-of-birds-on-branch-at-sunset-35240015/",
        credit: "Daan olde hanter",
      },
      keywordTag: "bird",
    },
    {
      afterParagraph: 4,
      image: {
        url: "https://images.pexels.com/photos/15231172/pexels-photo-15231172.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/view-of-an-egret-standing-in-the-grass-15231172/",
        credit: "Soonam Wooeser",
      },
      keywordTag: "home",
    },
  ],
  16: [
    {
      afterParagraph: 2,
      image: {
        url: "https://images.pexels.com/photos/8865662/pexels-photo-8865662.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/an-elderly-woman-sleeping-peacefully-on-her-bed-8865662/",
        credit: "RDNE Stock project",
      },
      keywordTag: "bedtime",
    },
    {
      afterParagraph: 5,
      image: {
        url: "https://images.pexels.com/photos/6591637/pexels-photo-6591637.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/overhead-shot-of-a-girl-smiling-while-listening-to-a-bedtime-story-6591637/",
        credit: "cottonbro studio",
      },
      keywordTag: "family",
    },
  ],
  17: [
    {
      afterParagraph: 2,
      image: {
        url: "https://images.pexels.com/photos/8556000/pexels-photo-8556000.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/silhouette-of-trees-during-sunset-8556000/",
        credit: "Tom Fisk",
      },
      keywordTag: "river",
    },
    {
      afterParagraph: 4,
      image: {
        url: "https://images.pexels.com/photos/36327899/pexels-photo-36327899.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/stunning-sunset-over-the-mississippi-river-36327899/",
        credit: "Tom Fisk",
      },
      keywordTag: "bird",
    },
  ],
  18: [
    {
      afterParagraph: 2,
      image: {
        url: "https://images.pexels.com/photos/7717181/pexels-photo-7717181.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/beautiful-sunset-over-a-still-lake-7717181/",
        credit: "Tom Fisk",
      },
      keywordTag: "river",
    },
    {
      afterParagraph: 4,
      image: {
        url: "https://images.pexels.com/photos/28405458/pexels-photo-28405458.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/serene-river-landscape-with-reflection-at-dusk-28405458/",
        credit: "Krzysztof Jaworski-Fotografia",
      },
      keywordTag: "bird",
    },
  ],
  19: [
    {
      afterParagraph: 2,
      image: {
        url: "https://images.pexels.com/photos/29690643/pexels-photo-29690643.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/seagull-in-flight-over-tranquil-water-at-dusk-29690643/",
        credit: "nis_ vagabond",
      },
      keywordTag: "bird",
    },
    {
      afterParagraph: 4,
      image: {
        url: "https://images.pexels.com/photos/33578023/pexels-photo-33578023.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/dramatic-sky-with-birds-and-soft-clouds-at-sunset-33578023/",
        credit: "Tuğba",
      },
      keywordTag: "family",
    },
  ],
  20: [
    {
      afterParagraph: 2,
      image: {
        url: "https://images.pexels.com/photos/5650815/pexels-photo-5650815.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/mysterious-forest-landscape-5650815/",
        credit: "Gabriel Conchinhas",
      },
      keywordTag: "forest",
    },
    {
      afterParagraph: 5,
      image: {
        url: "https://images.pexels.com/photos/2080963/pexels-photo-2080963.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/forest-at-night-2080963/",
        credit: "Johannes Plenio",
      },
      keywordTag: "river",
    },
  ],
  21: [
    {
      afterParagraph: 2,
      image: {
        url: "https://images.pexels.com/photos/5833950/pexels-photo-5833950.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/silhouette-of-a-bird-flying-in-the-sky-5833950/",
        credit: "Nick Wehrli",
      },
      keywordTag: "bird",
    },
    {
      afterParagraph: 4,
      image: {
        url: "https://images.pexels.com/photos/3642190/pexels-photo-3642190.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/perched-bird-3642190/",
        credit: "Lucas Sanchez",
      },
      keywordTag: "family",
    },
  ],
  22: [
    {
      afterParagraph: 2,
      image: {
        url: "https://images.pexels.com/photos/14421059/pexels-photo-14421059.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/a-trees-on-the-forest-14421059/",
        credit: "Michael Pointner",
      },
      keywordTag: "forest",
    },
    {
      afterParagraph: 5,
      image: {
        url: "https://images.pexels.com/photos/15296464/pexels-photo-15296464.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/sun-shining-on-trail-through-treees-15296464/",
        credit: "Vitali Adutskevich",
      },
      keywordTag: "bird",
    },
  ],
  23: [
    {
      afterParagraph: 2,
      image: {
        url: "https://images.pexels.com/photos/30499631/pexels-photo-30499631.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/serene-crescent-moon-in-cloudy-night-sky-30499631/",
        credit: "Jaweria Fatima",
      },
      keywordTag: "moon",
    },
    {
      afterParagraph: 4,
      image: {
        url: "https://images.pexels.com/photos/12690563/pexels-photo-12690563.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/full-moon-in-the-sky-12690563/",
        credit: "Debanjan Chatterjee",
      },
      keywordTag: "river",
    },
  ],
  24: [
    {
      afterParagraph: 2,
      image: {
        url: "https://images.pexels.com/photos/12966752/pexels-photo-12966752.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/brown-painting-on-yellow-background-12966752/",
        credit: "Marek Piwnicki",
      },
      keywordTag: "dragon",
    },
    {
      afterParagraph: 5,
      image: {
        url: "https://images.pexels.com/photos/29223698/pexels-photo-29223698.png?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/fiery-dragon-with-dynamic-light-trails-29223698/",
        credit: "Krizalid Daza",
      },
      keywordTag: "river",
    },
  ],
  25: [
    {
      afterParagraph: 2,
      image: {
        url: "https://images.pexels.com/photos/13876889/pexels-photo-13876889.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/green-trees-beside-body-of-water-13876889/",
        credit: "Siarhei Nester",
      },
      keywordTag: "river",
    },
    {
      afterParagraph: 4,
      image: {
        url: "https://images.pexels.com/photos/12785148/pexels-photo-12785148.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/a-river-during-a-twilight-12785148/",
        credit: "RAVI  LAGES",
      },
      keywordTag: "home",
    },
  ],
  26: [
    {
      afterParagraph: 2,
      image: {
        url: "https://images.pexels.com/photos/35001307/pexels-photo-35001307.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/birds-silhouetted-against-sunset-sky-35001307/",
        credit: "Md Mamun  Miah",
      },
      keywordTag: "bird",
    },
    {
      afterParagraph: 5,
      image: {
        url: "https://images.pexels.com/photos/6595046/pexels-photo-6595046.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/a-man-lying-on-the-bed-6595046/",
        credit: "cottonbro studio",
      },
      keywordTag: "home",
    },
  ],
  27: [
    {
      afterParagraph: 2,
      image: {
        url: "https://images.pexels.com/photos/5801248/pexels-photo-5801248.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/a-mother-putting-her-daughter-to-sleep-5801248/",
        credit: "cottonbro studio",
      },
      keywordTag: "home",
    },
    {
      afterParagraph: 4,
      image: {
        url: "https://images.pexels.com/photos/7609139/pexels-photo-7609139.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/vintage-telephone-beside-the-bed-7609139/",
        credit: "cottonbro studio",
      },
      keywordTag: "family",
    },
  ],
  28: [
    {
      afterParagraph: 2,
      image: {
        url: "https://images.pexels.com/photos/16158983/pexels-photo-16158983.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/forest-by-the-river-in-winter-16158983/",
        credit: "Tom Fisk",
      },
      keywordTag: "river",
    },
    {
      afterParagraph: 4,
      image: {
        url: "https://images.pexels.com/photos/8971853/pexels-photo-8971853.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/river-during-sunset-8971853/",
        credit: "Tom Fisk",
      },
      keywordTag: "bird",
    },
  ],
  29: [
    {
      afterParagraph: 2,
      image: {
        url: "https://images.pexels.com/photos/1612726/pexels-photo-1612726.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/shallow-focus-photography-of-table-lamp-1612726/",
        credit: "Juan Pablo Serrano",
      },
      keywordTag: "home",
    },
    {
      afterParagraph: 4,
      image: {
        url: "https://images.pexels.com/photos/235278/pexels-photo-235278.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/clear-and-brown-table-lamp-235278/",
        credit: "aj povey",
      },
      keywordTag: "family",
    },
  ],
  30: [
    {
      afterParagraph: 2,
      image: {
        url: "https://images.pexels.com/photos/5113938/pexels-photo-5113938.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/sunset-over-river-5113938/",
        credit: "Marco Milanesi",
      },
      keywordTag: "river",
    },
    {
      afterParagraph: 5,
      image: {
        url: "https://images.pexels.com/photos/34774279/pexels-photo-34774279.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/serene-sunset-over-calm-river-with-bridge-34774279/",
        credit: "Rain Lü",
      },
      keywordTag: "bird",
    },
  ],
  31: [
    {
      afterParagraph: 2,
      image: {
        url: "https://images.pexels.com/photos/31728410/pexels-photo-31728410.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/cozy-warm-bedroom-with-soft-lighting-atmosphere-31728410/",
        credit: "Đậu Photograph",
      },
      keywordTag: "home",
    },
    {
      afterParagraph: 4,
      image: {
        url: "https://images.pexels.com/photos/8036754/pexels-photo-8036754.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/photo-of-laptop-on-bed-8036754/",
        credit: "SHVETS production",
      },
      keywordTag: "family",
    },
  ],
  32: [
    {
      afterParagraph: 2,
      image: {
        url: "https://images.pexels.com/photos/21314267/pexels-photo-21314267.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/river-in-forest-at-dusk-21314267/",
        credit: "Tom Fisk",
      },
      keywordTag: "river",
    },
    {
      afterParagraph: 5,
      image: {
        url: "https://images.pexels.com/photos/5442677/pexels-photo-5442677.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/father-and-son-lying-on-the-bed-5442677/",
        credit: "Werner Pfennig",
      },
      keywordTag: "family",
    },
  ],
  33: [
    {
      afterParagraph: 2,
      image: {
        url: "https://images.pexels.com/photos/35372393/pexels-photo-35372393.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/cozy-winter-market-stall-with-warm-lights-35372393/",
        credit: "Alexander Popadin",
      },
      keywordTag: "bird",
    },
    {
      afterParagraph: 4,
      image: {
        url: "https://images.pexels.com/photos/35993523/pexels-photo-35993523.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/cozy-ceramic-lamps-display-at-dublin-market-35993523/",
        credit: "atelierbyvineeth . . .",
      },
      keywordTag: "market",
    },
  ],
  34: [
    {
      afterParagraph: 2,
      image: {
        url: "https://images.pexels.com/photos/10566108/pexels-photo-10566108.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/man-reading-book-to-his-daughter-10566108/",
        credit: "RDNE Stock project",
      },
      keywordTag: "river",
    },
    {
      afterParagraph: 4,
      image: {
        url: "https://images.pexels.com/photos/10566114/pexels-photo-10566114.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/daughter-and-mother-reading-book-on-bed-10566114/",
        credit: "RDNE Stock project",
      },
      keywordTag: "family",
    },
  ],
  35: [
    {
      afterParagraph: 2,
      image: {
        url: "https://images.pexels.com/photos/1690355/pexels-photo-1690355.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/photo-of-a-pathway-1690355/",
        credit: "Johannes Plenio",
      },
      keywordTag: "forest",
    },
    {
      afterParagraph: 4,
      image: {
        url: "https://images.pexels.com/photos/27849308/pexels-photo-27849308.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/cesta-mezi-stromy-27849308/",
        credit: "Karel Drozda",
      },
      keywordTag: "bird",
    },
  ],
  36: [
    {
      afterParagraph: 2,
      image: {
        url: "https://images.pexels.com/photos/35970189/pexels-photo-35970189.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/half-moon-in-cloudy-blue-sky-at-twilight-35970189/",
        credit: "Stephen Leonardi",
      },
      keywordTag: "moon",
    },
    {
      afterParagraph: 4,
      image: {
        url: "https://images.pexels.com/photos/11722935/pexels-photo-11722935.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/half-moon-in-the-sky-11722935/",
        credit: "Erik Torres",
      },
      keywordTag: "bird",
    },
  ],
  37: [
    {
      afterParagraph: 2,
      image: {
        url: "https://images.pexels.com/photos/5442680/pexels-photo-5442680.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/mother-and-son-lying-on-the-bed-5442680/",
        credit: "Werner Pfennig",
      },
      keywordTag: "bird",
    },
    {
      afterParagraph: 4,
      image: {
        url: "https://images.pexels.com/photos/10565716/pexels-photo-10565716.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/father-and-daughter-smiling-while-reading-book-10565716/",
        credit: "RDNE Stock project",
      },
      keywordTag: "family",
    },
  ],
  38: [
    {
      afterParagraph: 2,
      image: {
        url: "https://images.pexels.com/photos/10565632/pexels-photo-10565632.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/father-reading-to-his-child-10565632/",
        credit: "RDNE Stock project",
      },
      keywordTag: "bird",
    },
    {
      afterParagraph: 4,
      image: {
        url: "https://images.pexels.com/photos/10565634/pexels-photo-10565634.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/father-reading-book-to-his-child-10565634/",
        credit: "RDNE Stock project",
      },
      keywordTag: "family",
    },
  ],
  39: [
    {
      afterParagraph: 2,
      image: {
        url: "https://images.pexels.com/photos/6591658/pexels-photo-6591658.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/a-father-reading-bedtime-story-to-his-daughter-6591658/",
        credit: "cottonbro studio",
      },
      keywordTag: "bird",
    },
    {
      afterParagraph: 4,
      image: {
        url: "https://images.pexels.com/photos/10565642/pexels-photo-10565642.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        source: "pexels",
        pageUrl: "https://www.pexels.com/photo/father-and-daughter-reading-in-bed-10565642/",
        credit: "RDNE Stock project",
      },
      keywordTag: "family",
    },
  ],
};
